name: pbl5
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For State-Management
  flutter_bloc: ^8.1.3

  # For Assets
  flutter_gen: ^5.2.0
  flutter_svg: ^2.0.0
  lottie: ^2.6.0

  # For Localizations
  easy_localization: ^3.0.3

  # For Model
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

  # For Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1

  # For Utilities
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  shared_preferences: ^2.0.18
  connectivity_plus: ^4.0.1
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  emoji_picker_flutter: ^1.6.3
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1
  timeago: ^3.6.0

  # For Images, Files, Videos
  image_picker: ^1.0.2
  file_picker: ^5.3.1
  photo_view: ^0.14.0
  photo_manager: ^3.0.0-dev.5
  cached_network_image: ^3.2.3
  video_player: ^2.8.1
  chewie: ^1.7.4

  # Dynamic link & Firebase
  firebase_dynamic_links: ^5.4.8
  firebase_core: ^2.24.2
  onesignal_flutter: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # For Builder
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

  # For Model
  freezed: ^2.4.1

  # For Networking
  retrofit_generator: ^6.0.0+1
  device_preview: ^1.1.0

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_dash.png"

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/icons/
    - assets/htmls/
    - assets/lotties/
    - .env

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
